name: Wiki issue
description: Report a Wiki issue
title: "Wiki issue: "
labels: ["📄 Wiki issue"]
body:
  - type: input
    id: url
    attributes:
      label: "URL to the Wiki page"
      placeholder: "https://github.com/qdm12/gluetun/wiki/OpenVPN-options"
    validations:
      required: true
  - type: textarea
    id: description
    attributes:
      label: "What's the issue?"
    validations:
      required: true
